# -*- coding: utf-8 -*-
"""Untitled61.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFg-1vO9Mr2L_8BCo162Z_VVCrHEmDbv
"""

class Member:
    def __init__(self, member_id, name):
        self.id = member_id
        self.name = name

class MemberManage:
    def __init__(self):
        self.members = []

    def addMember(self, member):
        self.members.append(member)
        print(f"회원 추가: {member.name} (ID: {member.id})")

    def removeMember(self, member_id):
        for member in self.members:
            if member.id == member_id:
                self.members.remove(member)
                print(f"회원 삭제: {member.name} (ID: {member.id})")
                return
        print(f"ID가 {member_id}인 회원이 없습니다.")

    def printMember(self, member_id):
        for member in self.members:
            if member.id == member_id:
                print(f"회원 정보: {member.name} (ID: {member.id})")
                return
        print(f"ID가 {member_id}인 회원이 없습니다.")

    def printMembers(self):
        print("전체 회원 정보:")
        for member in self.members:
            print(f"{member.name} (ID: {member.id})")


# 테스트
if __name__ == "__main__":
    # 회원 관리 객체 생성
    member_manager = MemberManage()

    # 회원 추가
    while True:
        try:
            member_id = int(input("회원 ID를 입력하세요: "))
            member_name = input("회원 이름을 입력하세요: ")
            new_member = Member(member_id, member_name)
            member_manager.addMember(new_member)
        except ValueError:
            print("올바른 형식으로 입력하세요. ID는 정수여야 합니다.")

        add_more = input("더 회원을 추가하시겠습니까? (y/n): ")
        if add_more.lower() != 'y':
            break

    # 전체 회원 정보 출력
    member_manager.printMembers()

    # 회원 삭제
    while True:
        try:
            remove_id = int(input("삭제할 회원의 ID를 입력하세요: "))
            member_manager.removeMember(remove_id)
        except ValueError:
            print("올바른 형식으로 입력하세요. ID는 정수여야 합니다.")

        remove_more = input("더 회원을 삭제하시겠습니까? (y/n): ")
        if remove_more.lower() != 'y':
            break

    # 전체 회원 정보 출력
    member_manager.printMembers()

