# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HrCTZGe0xh8UjybTvhsAiNre8AQSjj6J
"""

# "./sales.txt" 파일을 읽고 데이터를 저장
with open("./sales.txt", 'r', encoding='utf-8') as file:
    data = file.read()

# 데이터를 줄 바꿈 문자("\n")를 기준으로 분할하고 필터링하고 정수로 변환
data_lines = data.split("\n")
data = [int(line[9:]) for line in data_lines if line]

# 데이터의 합계를 계산
data_sum = sum(data)

# 결과를 "sum.txt" 파일에 저장
with open("./sum.txt", 'w', encoding='utf-8') as file:
    file.write(f"총 매출 = {str(data_sum)}\n일일 평균매출 = {str(data_sum/30)}")

print(data_sum)