# -*- coding: utf-8 -*-
"""경고장,자동배정.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HziqlsHeR1RggMLSuJITN2EVXyjkANf5
"""

#자동배정
import random

class 시간표배정기:
    def __init__(self):
        self.timetable = [[None] * 5 for _ in range(6)]

    def 자동_수업_배정(self, 교수):
        for _ in range(100):
            day, time = random.randint(0, 5), random.randint(0, 4)
            if self.timetable[day][time] is None and sum(row.count(professor) for row in self.timetable) < 3:
                self.시간표[day][time] = professor
                return True
        return False

# 사용 예시:
scheduler  = TimetableScheduler()
professorname = "professorA"

success  = scheduler.auto_assign_course(professor_name)
if success:
    print(f"{교수명}님의 수업이 배정되었습니다.")
else:
    print("수업 배정에 실패했습니다. 교수님의 일정 또는 슬롯의 가용성을 확인해주세요.")


#경고창
import warnings

class TimetableScheduler:
    def __init__(self):
        self.timetable = [[None] * 5 for _ in range(6)]

    def assign_course(self, day, time, professor):
        if self.timetable[day][time] is not None:
            warnings.warn("이미 배정된 슬롯입니다. 다른 슬롯을 선택해주세요.")
            return False

        if sum(row.count(professor) for row in self.timetable) >= 3:
            warnings.warn(f"{professor} 교수님은 이미 3개 이상의 수업을 배정받았습니다.")
            return False

        self.timetable[day][time] = professor
        return True

scheduler = TimetableScheduler()
professor_name = "ProfessorA"

success = scheduler.assign_course(0, 0, professor_name)
if success:
    print(f"{professor_name} 교수님의 수업이 배정되었습니다.")
else:
    print("수업 배정에 실패했습니다. 교수님의 일정 또는 슬롯의 가용성을 확인해주세요.")